[workspace]
members = ["umbra-poc", "umbra-sdk", "umbra-content-types"]

default-members = ["umbra-poc", "umbra-sdk", "umbra-content-types"]

resolver = "3"

[workspace.package]
version = "0.0.1-dev"

[workspace.dependencies]
