[workspace]
members = [
    "umbra-content-types",
    "umbra-poc",
    "umbra-sdk",
    "umbra-types"
]

default-members = [
    "umbra-content-types",
    "umbra-poc",
    "umbra-sdk",
]

resolver = "3"

[workspace.package]
version = "0.0.1-dev"

[workspace.dependencies]


