[package]
name = "umbra-poc"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
umbra-content-types = { path = "../umbra-content-types" }
umbra-sdk = { path = "../umbra-sdk" }
