[package]
name = "umbra-poc"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
umbra-types = { path = "../umbra-types" }

[build-dependencies]
protoc-rust = "2"
