[package]
name = "umbra-sdk"
edition = "2024"
version.workspace = true

[dependencies]
hex = "0.4.3"
prost = "0.13.5"
rand = "0.9.1"
sha3 = "0.10.8"
thiserror = "2.0.12"
umbra-types = { path = "../umbra-types" }

[build-dependencies]

