[package]
name = "umbra-content-types"
edition = "2024"
version.workspace = true

[dependencies]
prost = "0.13.5"
bytes = "0.4"
umbra-types = { path = "../umbra-types" }

[build-dependencies]
prost-build = "0.13.5"
protoc-rust = "2"
